#ifndef __CAP_H__
#define __CAP_H__

#include <stdint.h>

#include "util.h"

#define CAP_RIGHT_MIGRATABLE BIT(0) //this cap may be migrated to another bottle

typedef uint64_t aeskey_t[2]; //AES keys are 128 bits

struct cap_t {
	aeskey_t key; //password is a AES-128 key, generated by issuer
	aeskey_t issuer; //issuer's AES-128 key
	uint64_t oid; //object-ID field, used by issuer
	uint64_t expiry; //cap expiry time, in unsigned 64-bit Unix time, determined by issuer
	uint32_t urights; //rights mask, used by issuer
	uint32_t srights; //BottleCap rights word, determined by issuer
	//Note: expiry == 0 -> slot is empty
};


#endif /* __CAP_H__ */

