#ifndef __BOTTLECAP_BOTTLECALLS_H__
#define __BOTTLECAP_BOTTLECALLS_H__

//call number enum
enum {
	BOTTLE_NULL = 0,
	BOTTLE_INIT,
	BOTTLE_DESTROY,
	BOTTLE_QUERY_FREE_SLOTS,
	BOTTLE_EXPIRE,
	BOTTLE_EXPORT,
	BOTTLE_IMPORT,
	BOTTLE_CAP_ADD,
	BOTTLE_CAP_DELETE,
	BOTTLE_CAP_EXPORT,
	BOTTLE_CAP_ATTEST,
	BOTTLE_TPM_QUOTE,
	BOTTLE_GENKEY,
};

//param type enum
enum {
	BOTTLE_CALL = 0x1000,
	BOTTLE_HEADER,
	BOTTLE_TABLE,
	BOTTLE_SLOTCOUNT,
	BOTTLE_EXPIRY,
	BOTTLE_INDEX,
	BOTTLE_CRYPTCAP,
	BOTTLE_NONCE,
	BOTTLE_URIGHTS,
	BOTTLE_TICKET,
//start debug entries here
	BOTTLE_PROFILING,
	BOTTLE_PCRS,
	BOTTLE_KEY,
	BOTTLE_KEYBLOB
};

#endif /* __BOTTLECAP_BOTTLECALLS_H__ */
